import { type IUserListFilter } from 'features/admin/users/interfaces/IUserListFilter';
import { type IWorkOrderListFilter } from 'features/admin/work-orders/interfaces/IWorkOrderListFilter';
import {
  type IActionModel,
  type IChartTemplateModel,
  type IConnectionModel,
  type IContributorModel,
  type IDataLocationModel,
  type IFilterModel,
  type IFolderModel,
  type IIngestModel,
  type IIngestTypeModel,
  type ILicenseModel,
  type IMediaTypeModel,
  type IMinisterModel,
  type INotificationModel,
  type INotificationTemplateModel,
  type IOrganizationModel,
  type IPaged,
  type IProductModel,
  type IReportModel,
  type IReportTemplateModel,
  type ISeriesModel,
  type ISettingModel,
  type ISourceModel,
  type ISystemMessageModel,
  type ITagModel,
  type ITopicModel,
  type ITopicScoreRuleModel,
  type IUserFilter,
  type IUserModel,
  type IWorkOrderModel,
} from 'tno-core';

export interface IAdminState {
  actionFilter: string;
  actions: IActionModel[];
  chartTemplates: IChartTemplateModel[];
  connectionFilter: string;
  connections: IConnectionModel[];
  contributorFilter: string;
  contributors: IContributorModel[];
  dataLocationFilter: string;
  dataLocations: IDataLocationModel[];
  folderFilter: string;
  folders: IFolderModel[];
  filterFilter: string;
  filters: IFilterModel[];
  ingestFilter: string;
  ingests: IIngestModel[];
  ingestTypeFilter: string;
  ingestTypes: IIngestTypeModel[];
  licenseFilter: string;
  licenses: ILicenseModel[];
  mediaTypeFilter: string;
  mediaTypes: IMediaTypeModel[];
  ministerFilter: string;
  ministers: IMinisterModel[];
  notificationFilter: string;
  notifications: INotificationModel[];
  notificationTemplates: INotificationTemplateModel[];
  organizationFilter: string;
  organizations: IOrganizationModel[];
  productFilter: string;
  products: IProductModel[];
  reportFilter: string;
  reportSubscriberFilter: IUserFilter;
  reports: IReportModel[];
  reportTemplates: IReportTemplateModel[];
  rules: ITopicScoreRuleModel[];
  seriesFilter: string;
  series: ISeriesModel[];
  sourceFilter: string;
  sources: ISourceModel[];
  systemMessages: ISystemMessageModel[];
  tagFilter: string;
  tags: ITagModel[];
  topicFilter: string;
  topics: ITopicModel[];
  userFilter: IUserListFilter;
  users: IPaged<IUserModel>;
  workOrderFilter: IWorkOrderListFilter;
  workOrders: IPaged<IWorkOrderModel>;
  settings: ISettingModel[];
}
