apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 9b301c-prod
commonLabels:
  env: prod
resources:
  - ../../base
images:
  - name: bcgov-c4awhwfpcremdbga.azurecr.io/fileupload-service
    newTag: prod

