namespace TNO.Entities;

/// <summary>
/// ReportType enum, provides a way to identify different types of reports.
/// </summary>
public enum ReportType
{
    /// <summary>
    /// A custom report is a manually selected list of content.
    /// </summary>
    Custom = 0,
    /// <summary>
    /// A filter report is auto generated by a filter.
    /// </summary>
    Filter = 1,
}
