---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 9b301c-dev

resources:
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: elastic
    type: stringData
    env: secret.env

# Add the following files to this folder
# They should contain the tls routes with the certificate information.
patchesStrategicMerge:
  - route.env

patches:
  - target:
      kind: Route
      name: elastic
    patch: |-
      - op: replace
        path: /spec/host
        value: dev.mmi.gov.bc.ca
  - target:
      kind: StatefulSet
      name: elastic
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 300m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 2Gi
      - op: add
        path: /spec/template/spec/containers/0/resources/limits
        value:
          cpu: "2"
          memory: 3Gi
