---
kind: ConfigMap
apiVersion: v1
metadata:
  name: smtp-retry-service
  namespace: default
  annotations:
    description: SMTP retry service configuration settings
    created-by: jeremy.foster
  labels:
    name: smtp-retry-service
    part-of: tno
    version: 1.0.0
    component: smtp-retry-service
    managed-by: kustomize
data:
  MAX_FAIL_LIMIT: "5"
  SMTP_EMAIL_ENABLED: "true"
  SMTP_EMAIL_AUTHORIZED: "true"
  RETRY_TIME_LIMIT: "5"
  RETRY_TIME_SCOPE: "60"
