---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 9b301c-prod

resources:
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      kind: Deployment
      name: automation-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: bcgov-c4awhwfpcremdbga.azurecr.io/automation-service:prod
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 512Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
