apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 9b301c-dev
commonLabels:
  env: dev
resources:
  - ../../base
images:
  - name: bcgov-c4awhwfpcremdbga.azurecr.io/fileupload-service
    newTag: dev
patches:
  - target:
      kind: ConfigMap
      name: fileupload-service
    patch: |-
      - op: replace
        path: /data/DAYS_BEFORE_START
        value: "365"
      - op: replace
        path: /data/DAYS_BEFORE_END
        value: "1"

