export enum AdvancedSearchKeys {
  Id = 'id',
  Headline = 'headline',
  Story = 'story',
  Source = 'sourceIds',
  Byline = 'byline',
  Section = 'section',
  Page = 'pageName',
  Status = 'status',
  Edition = 'edition',
  ContentType = 'contentType',
  PublishedOn = 'publishedOn',
  CreatedOn = 'createdOn',
  UpdatedOn = 'updatedOn',
}
