import { ContentStatusName, ContentTypeName } from '../constants';
import { IFilterActionSettingsModel, ISortField } from '.';

export interface IFilterSettingsModel {
  searchUnpublished: boolean;
  id?: number;
  from?: number;
  size: number;
  defaultSearchOperator?: 'and' | 'or';
  boldKeywords?: boolean;
  contentIds?: number[];
  contentTypes?: ContentTypeName[];
  contributorIds?: number[];
  edition?: string;
  headline?: string;
  summary?: string;
  body?: string;
  featured?: boolean;
  hasTopic?: boolean;
  inByline?: boolean;
  inHeadline?: boolean;
  inStory?: boolean;
  inProgram?: boolean;
  isHidden?: boolean;
  mediaTypeIds?: number[];
  names?: string;
  otherSource?: string;
  ownerId?: number;
  page?: string;
  search?: string;
  section?: string;
  sentiment?: number[];
  seriesIds?: number[];
  actions?: IFilterActionSettingsModel[];
  sourceIds?: number[];
  tags?: string[];
  dateOffset?: number;
  startDate?: string;
  endDate?: string;
  publishedOn?: string;
  startPostedDate?: string;
  endPostedDate?: string;
  createdOn?: string;
  updatedOn?: string;
  status?: ContentStatusName;
  userId?: number;
  sort?: ISortField[];
}
