import { ContentStatus, ContentTypeName } from '../constants';
import { ISortPageFilter } from '.';

export interface ISubscriberContentFilter extends ISortPageFilter {
  actions?: string[];
  boldKeywords?: boolean;
  byline?: string;
  contentTypes: ContentTypeName[];
  contributorIds?: number[];
  createdEndOn?: string;
  createdOn?: string;
  createdStartOn?: string;
  edition?: string;
  excludeSourceIds?: number[];
  hasFile?: boolean;
  hasTopic?: boolean;
  headline?: string;
  inByline?: boolean;
  inHeadline?: boolean;
  inStory?: boolean;
  isHidden?: boolean;
  keyword?: string;
  mediaTypeIds?: number[];
  names?: string;
  onlyHidden?: boolean;
  onlyPublished?: boolean;
  otherSource?: string;
  ownerId?: number;
  pageName?: string;
  paperPage?: string;
  publishedEndOn?: string;
  publishedOn?: string;
  publishedStartOn?: string;
  quantity?: number;
  searchTerm?: string;
  searchUnpublished?: boolean;
  section?: string;
  sentiment?: number[];
  seriesIds?: number[];
  sourceIds?: number[];
  status?: ContentStatus;
  storyText?: string;
  tags?: string[];
  updatedEndOn?: string;
  updatedOn?: string;
  updatedStartOn?: string;
  userId?: number;
}
