export const defaultAdvancedSearch = {
  boldKeywords: true,
  contentTypes: [],
  contributorIds: [],
  dateOffset: 1,
  edition: '',
  frontPage: false,
  hasFile: false,
  inByline: true,
  inHeadline: true,
  inStory: true,
  mediaTypeIds: [],
  page: '',
  publishedEndOn: '',
  publishedStartOn: '',
  searchTerm: '',
  section: '',
  seriesIds: [],
  sourceIds: [],
  tags: [],
  topStory: false,
  useUnpublished: false,
};
