DO $$
BEGIN

-- Populate a temp table with the matching values.
CREATE TEMP TABLE _series_source AS
WITH vals ("source", "series") AS (
  VALUES
  ('APTN', 'APTN National News')
  , ('CBC', 'CBC All Points West')
  , ('CBC', 'CBC As It Happens')
  , ('CBC', 'CBC BC Today')
  , ('CBC', 'CBC Daybreak Kamloops')
  , ('CBC', 'CBC Daybreak North')
  , ('CBC', 'CBC Daybreak South')
  , ('CBC', 'CBC Early Edition')
  , ('CBC', 'CBC News Vancouver')
  , ('CBC', 'CBC Newsworld')
  , ('CBC', 'CBC On the Coast')
  , ('CBC', 'CBC On the Island')
  , ('CBC', 'CBC Power & Politics')
  , ('CBC', 'CBC Radio West')
  , ('CBC', 'CBC The Current')
  , ('CBC', 'CBC The House')
  , ('CFAX', 'CFAX Adam Stirling')
  , ('CFAX', 'CFAX Bill Carroll')
  , ('CFAX', 'CFAX Evan Solomon')
  , ('CFAX', 'CFAX Ian Jessop')
  , ('CFAX', 'CFAX Mornings with Al Ferraby')
  , ('CFAX', 'CFAX Noon Show')
  , ('CFAX', 'CFAX Ryan Price')
  , ('CFJC', 'CFJC Evening News')
  , ('CFJC', 'CFJC Noon News')
  , ('CFTV', 'CFTV Fairchild Evening News')
  , ('CHBC', 'CHBC News at 5:00')
  , ('CHBC', 'CHBC News at 6:30')
  , ('CHEK', 'CHEK News at Five')
  , ('CHEK', 'CHEK Political Capital with Rob Shaw')
  , ('CHKG', 'CHKG')
  , ('CHMB', 'CHMB')
  , ('CHNL', 'CHNL')
  , ('CHNL', 'CHNL Brett Mineer')
  , ('CHNL', 'CHNL Jeff Andreas')
  , ('CHNL', 'CHNL Paul James')
  , ('CHNM', 'CHNM Omni Cantonese')
  , ('CN', 'CityNews1130')
  , ('CJCN', 'CJCN Vasu Kumar')
  , ('CJCN', 'CJCN Vijay Saini')
  , ('CJVB', 'CJVB')
  , ('CJVB', 'CJVB News Hotline')
  , ('CJVB', 'CJVB Online')
  , ('CKFR', 'CKFR Phil Johnson')
  , ('CKFU', 'CKFU')
  , ('CKNW', 'CKNW')
  , ('CKNW', 'CKNW Jas Johal')
  , ('CKNW', 'CKNW Jill Bennett')
  , ('CKNW', 'CKNW Mike Smyth')
  , ('CKNW', 'CKNW Mike Smyth: Baldrey''s Beat')
  , ('CKNW', 'CKNW Online')
  , ('CKNW', 'CKNW Simi Sara')
  , ('CKNW', 'CKNW Simi Sara: View From Victoria')
  , ('CKNW', 'CKNW Weekend Show')
  , ('CKPG', 'CKPG at 5:00')
  , ('CKPG', 'CKPG at Noon')
  , ('CKSP', 'CKSP Sameer Kaushal')
  , ('CKWX', 'CKWX Online')
  , ('CKYE', 'CKYE')
  , ('CKYE', 'CKYE Harjinder Thind')
  , ('CP', 'CP News')
  , ('CTV', 'CTV Canada AM')
  , ('CTV', 'CTV Morning Live')
  , ('CTV', 'CTV News at Five')
  , ('CTV', 'CTV News at Noon')
  , ('CTV', 'CTV News at Six')
  , ('CTV', 'CTV News Channel')
  , ('CTV', 'CTV News Live @ 5')
  , ('CTV', 'CTV News Live @ 6')
  , ('BC1', 'Focus BC with Richard Zussman')
  , ('CHAN', 'Global BC Early News')
  , ('CHAN', 'Global BC Morning News')
  , ('CHAN', 'Global BC News Hour')
  , ('CHAN', 'Global BC Noon News')
  , ('BC1', 'Global News: BC 1')
  , ('CKNW', 'Michael Smyth')
  , ('CHEK', 'Political Capital with Rob Shaw')
  , ('CKNW', 'View from Victoria')
)
SELECT * FROM vals;

END $$;
