export enum ReportTypeName {
  /// <summary>
  /// A custom report is a manually selected list of content.
  /// </summary>
  Custom = 'Custom',
  /// <summary>
  /// A filter report is auto generated by a filter.
  /// </summary>
  Filter = 'Filter',
}
