GRANT CONNECT ON DATABASE tno TO admin;
GRANT USAGE ON SCHEMA public TO admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON DATABASE tno TO admin;

ALTER USER admin WITH SUPERUSER;
ALTER USER admin WITH NOSUPERUSER;

ALTER DEFAULT PRIVILEGES FOR USER admin GRANT USAGE ON SCHEMAS TO admin;
ALTER DEFAULT PRIVILEGES FOR USER admin IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO admin;
ALTER DEFAULT PRIVILEGES FOR USER admin IN SCHEMA public GRANT ALL ON SEQUENCES TO admin;
ALTER DEFAULT PRIVILEGES FOR USER admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO admin;
