-- ALTER SESSION SET CONTAINER = ORCLPDB1;
-- ALTER SESSION SET CONTAINER = XE;
ALTER SESSION SET CONTAINER = FREEPDB1;

-- Reset the TNO_USER
DROP USER TNO_USER CASCADE;
ALTER TABLESPACE TNO_USER OFFLINE;
DROP TABLESPACE TNO_USER INCLUDING CONTENTS;

CREATE USER TNO_USER IDENTIFIED BY "TnoVsMmia2023";