-- ALTER SESSION SET CONTAINER = ORCLPDB1;
-- ALTER SESSION SET CONTAINER = XE;
ALTER SESSION SET CONTAINER = FREEPDB1;

-- Reset the TNO
DROP USER TNO CASCADE;
ALTER TABLESPACE TNO OFFLINE;
DROP TABLESPACE TNO INCLUDING CONTENTS;

CREATE USER TNO IDENTIFIED BY "TnoVsMmia2023";

CREATE USER READONLY IDENTIFIED BY "TnoVsMmia2023";