-- ALTER SESSION SET CONTAINER = ORCLPDB1;
-- ALTER SESSION SET CONTAINER = XE;
ALTER SESSION SET CONTAINER = FREEPDB1;

GRANT CONNECT TO tno_user CONTAINER=CURRENT;
GRANT CREATE SESSION TO tno_user CONTAINER=CURRENT;
GRANT RESOURCE TO tno_user CONTAINER=CURRENT;

ALTER USER tno_user QUOTA 100M ON USERS;