-- ALTER SESSION SET CONTAINER = ORCLPDB1;
-- ALTER SESSION SET CONTAINER = XE;
ALTER SESSION SET CONTAINER = FREEPDB1;

GRANT CONNECT TO TNO CONTAINER=CURRENT;
GRANT CREATE SESSION TO TNO CONTAINER=CURRENT;
GRANT RESOURCE TO TNO CONTAINER=CURRENT;

GRANT CREATE session TO TNO;
GRANT CREATE table TO TNO;
GRANT CREATE view TO TNO;
GRANT CREATE any trigger TO TNO;
GRANT CREATE any procedure TO TNO;
GRANT CREATE sequence TO TNO;
GRANT CREATE synonym TO TNO;

GRANT CONNECT TO READONLY CONTAINER=CURRENT;
GRANT CREATE SESSION TO READONLY CONTAINER=CURRENT;
GRANT RESOURCE TO READONLY CONTAINER=CURRENT;

ALTER USER TNO QUOTA 100M ON USERS;