FROM confluentinc/cp-kafka:7.6.1

USER root

RUN chgrp -R root /var/log/kafka && \
  chmod -R g=u /var/log/kafka

WORKDIR /app
COPY ./entrypoint.sh .
RUN chmod +x entrypoint.sh
RUN chown -R appuser:root /var/log/kafka /var/log/confluent /var/lib/kafka/data /app

USER appuser

ENTRYPOINT ["/app/entrypoint.sh"]
# ENTRYPOINT ["tail", "-f", "/dev/null"]

