import { AISectionStatusName, IReportAISectionStatusModel } from '../../hooks';

/**
 * Whether any AI section of a preview is still waiting for, or being generated by, the reporting service.
 * @param sections The AI section states returned with the preview.
 * @returns True while the preview will be updated when its AI sections are ready.
 */
export const isAISectionPending = (sections?: IReportAISectionStatusModel[]) =>
  !!sections?.some(
    (s) =>
      s.status === AISectionStatusName.NotStarted || s.status === AISectionStatusName.Generating,
  );
