name: API Services CI/CD

on:
  workflow_dispatch:
  pull_request:
    branches: [dev, master]
    paths:
      - api/net/**
      - libs/net/**
      - openshift/kustomize/api-services/**
      - .github/workflows/api-services-cicd.yml
  push:
    branches: [dev, master, folder-collection]
    paths:
      - api/net/**
      - libs/net/**
      - openshift/kustomize/api-services/**
      - .github/workflows/api-services-cicd.yml

concurrency:
  group: api-services-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    uses: ./.github/workflows/_reusable-dotnet-cicd.yml
    with:
      image_name: api
      csproj_path: api/net/TNO.API.csproj
      dockerfile: api/net/Dockerfile
      component: api-services
      deployment_name: api-services
      kustomize_dev_path: openshift/kustomize/api-services/overlays/dev
      kustomize_test_path: openshift/kustomize/api-services/overlays/test
      dev_branch: folder-collection
      rollout_timeout: '600s'
      continue_on_error_verify: true
      health_check_method: port_forward
    secrets:
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
