name: Auto Deploy
run-name: Auto Deploy to ${{ fromJSON('{"refs/heads/dev":"dev","refs/heads/master":"test"}')[github.ref] }} from ${{ github.ref_name }}

on:
  push:
    branches: [dev, master]
    paths:
      - api/**
      - app/**
      - services/**
      - libs/**
      - openshift/**
      - .github/workflows/auto-deploy.yml
      - .github/workflows/deploy-all.yml
      - .github/scripts/**

permissions:
  contents: read
  security-events: write

jobs:
  deploy:
    if: ${{ contains(fromJSON('["refs/heads/dev", "refs/heads/master"]'), github.ref) }}
    uses: ./.github/workflows/deploy-all.yml
    with:
      environment: ${{ fromJSON('{"refs/heads/dev":"dev","refs/heads/master":"test"}')[github.ref] }}
      skip_db_migration: false
      deploy_scope: changed
    secrets:
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
