name: Auto Deploy

on:
  push:
    branches: [dev,auto_deployment_test]
    paths:
      - api/**
      - app/**
      - services/**
      - libs/**
      - openshift/**
      - .github/workflows/auto-deploy.yml
      - .github/workflows/deploy-all.yml
      - .github/scripts/**

jobs:
  deploy:
    uses: ./.github/workflows/deploy-all.yml
    with:
      environment: dev
      skip_db_migration: false
      deploy_scope: changed
    secrets:
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
