DO $$
BEGIN

CREATE TEMP TABLE _tag AS
SELECT "id", "code", "name"
FROM public.tag;

ALTER TABLE public.content_tag DROP CONSTRAINT "FK_content_tag_tag_tag_id";

ALTER TABLE public.tag ALTER COLUMN "id" DROP IDENTITY IF EXISTS;

ALTER TABLE public.tag ALTER COLUMN "id" SET DATA TYPE varchar USING "id"::varchar;

UPDATE public.tag
SET "id" = _tag.code
FROM _tag
WHERE _tag.code = public.tag.code;

ALTER TABLE public.content_tag ALTER COLUMN "tag_id" SET DATA TYPE varchar USING "tag_id"::varchar;

UPDATE public.content_tag
SET "tag_id" = _tag.code
FROM _tag
WHERE _tag.id::varchar = public.content_tag.tag_id;

ALTER TABLE public.content_tag ADD CONSTRAINT "FK_content_tag_tag_tag_id" FOREIGN KEY ("tag_id") REFERENCES public.tag ("id") ON DELETE CASCADE;
-- add identity to id back to column
-- ALTER TABLE public.tag ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;

DROP TABLE _tag;

END $$;
